name: Scheduled / Crone Job Checking the test [Every day at 11:11 AM]
on: 
  schedule:
    - cron: "11 11 * * *"

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Kolkata' 
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run ${{ secrets.COLLECTION_ID }}
